version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build production started
      - ng build --configuration=production
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist*'
